### PR TITLE
Add constant for setting table back down

### PR DESCRIPTION
**Pull request by colinodell**
`┬─┬﻿ノ(･_･ノ);`

### CODE REVIEW

**Comment by sgolemon** [comment]
I like the sentiment, but shouldn't setting the table down actually *do* something?

**Comment by sgolemon** [comment]
And if it really shouldn't do anything, then maybe make it not a function call at all:

`const ┬─┬﻿ノ（･_･ノ） = '';`

Then `┬─┬﻿ノ（･_･ノ）;` is a full no-op once the useless constant fetch is eliminated.

**Comment by colinodell** [comment]
I like the constant idea, I'll make that change :)

**Comment by colinodell** [comment]
Re-implemented as constant, amended commit, and force-pushed.

**Pull request merged**
